spring.application.name=UniOps_Smart-Campus-Operations-Hub-PAF
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://UniOpsUser:uniopsuniops@uniops.qyyx7e2.mongodb.net/uniops?retryWrites=true&w=majority&appName=uniops}
spring.data.mongodb.database=${MONGODB_DATABASE:uniops}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
jwt.secret=smartcampus-super-secret-jwt-key-2026-sliit-it3030
jwt.expiration=86400000
app.auth.admin.username=admin@university.edu
app.auth.admin.password=admin123
spring.profiles.active=dev

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=janakashan190@gmail.com
spring.mail.password=binn fiwq tljv pwdq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

