logging.level.com.uniops=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN
logging.level.org.mongodb.driver=ERROR
logging.level.org.springframework.data.mongodb=ERROR
