spring.application.name=smartcampus
server.port=8086

# MongoDB Connection Configuration
# TODO: Replace with your own MongoDB Atlas URI in your local application.properties
spring.data.mongodb.uri=mongodb+srv://<YOUR_USERNAME>:<YOUR_PASSWORD>@paf.9pqijns.mongodb.net/Uni_Ops?appName=PAF

# Google OAuth Configuration
# TODO: Add your Google Client ID and Secret in your local application.properties
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID_HERE
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET_HERE
spring.security.oauth2.client.registration.google.scope=profile,email

# Allow larger image uploads for facilities
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB